### ISSUE TITLE
FV zoom stops working after maximize button

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-ui#46]
For:
* idaes-pse==2.3.0
* idaes-ui==0.23.12

After using the "maximize" button (diagonal line with arrows at each end) on the visualizer diagram pane, the zoom in/out stops working.

**Comment by CopyDemon** [comment]
This issue arises because the flowsheet display is not cleared promptly. Whenever the state is updated in React, it triggers a DOM rerender, resulting in the new flowsheet display being appended below the previous one. The zoom-in and zoom-out buttons control only the latest flowsheet display. Since the frame of the flowsheet display is set to overflow-y:hidden, any changes remain invisible.

<img width="2160" alt="image" src="https://github.com/IDAES/idaes-ui/assets/27743177/927f59d7-274e-469a-a53d-400992fe73db">

PR #47

**Comment by CopyDemon** [comment]
new Issue shows up:
1. fix the flowsheet zoom out and disappear.
2. remove the maximize button from the flowsheet header, and add the minimize button to the stream table header.
